[[redirects]]
  from = "/"
  to = "web/index.html"
  status = 200

# Web alias
[[redirects]]
  from = "/web/*"
  to = "web/index.html"
  status = 200

# Raffle alias
[[redirects]]
  from = "/raffle/*"
  to = "https://raffle-dehub.netlify.app/raffle/:splat"
  status = 200
  force = true
