[[redirects]]
  from = "/"
  to = "web/index.html"
  status = 200

[[redirects]]
  from = "/web/*"
  to = "web/index.html"
  status = 200

# Raffle
[[redirects]]
  from = "/raffle/*"
  to = "https://raffle-dehub.netlify.app/raffle/:splat"
  status = 200
  force = true

# Prediction
[[redirects]]
  from = "/prediction/*"
  to = "https://prediction-dehub.netlify.app/prediction/:splat"
  status = 200
  force = true
