[[redirects]]
  from = "/"
  to = "staking/index.html"
  status = 200

[[redirects]]
  from = "/staking/*"
  to = "staking/index.html"
  status = 200

# Web
[[redirects]]
  from = "/web/*"
  to = "https://dapps-dehub.netlify.app/web/:splat"
  status = 200
  force = true

# Prediction
[[redirects]]
  from = "/prediction/*"
  to = "https://prediction-dehub.netlify.app/prediction/:splat"
  status = 200
  force = true
