# Documentation
# https://nx.app/docs/configuring-ci

# Curtesy for Jo Hanna Pearce for the idea
# https://github.com/jdpearce/nx-large-repo/actions/runs/2229075101/workflow
name: DeHUB Nx
on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: '16'
  INSTALL_CMD: 'npm ci --legacy-peer-deps'

# Each push should cancel workflows in progress and start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    if: ${{ github.event_name != 'pull_request' }}
    name: Main
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.4
    with:
      node-version: ${{ github.env.NODE_VERSION }}
      install-commands: |
        ${{ github.env.INSTALL_CMD }}
      parallel-commands-on-agents: |
        npm run lint
        npm run test
        npm run build
        npm run build:preview
        NX_CLOUD_DISTRIBUTED_EXECUTION=false npm run deploy:preview
        NX_CLOUD_DISTRIBUTED_EXECUTION=false npm run deploy:prod

  pr:
    if: ${{ github.event_name == 'pull_request' }}
    name: Pull Request
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.4
    with:
      node-version: ${{ github.env.NODE_VERSION }}
      install-commands: |
        ${{ github.env.INSTALL_CMD }}
      parallel-commands-on-agents: |
        npm run lint
        npm run test
        npm run build:preview
        NX_CLOUD_DISTRIBUTED_EXECUTION=false npm run deploy:preview-draft

  agents:
    name: Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.4
    with:
      node-version: ${{ github.env.NODE_VERSION }}
      install-commands: |
        ${{ github.env.INSTALL_CMD }}
      number-of-agents: 3
